// <auto-generated />
namespace SaminProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class news_add_propDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(news_add_propDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201902241140212_news_add_propDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
